import { z } from "zod";
import { authenticateDevice } from "@/lib/api/auth-device";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";

// GET — pull latest config for this device
export async function GET(request: Request) {
  const device = await authenticateDevice(request);
  if (!device) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (!device.capabilities.config) {
    return Response.json({ error: "Device does not support config" }, { status: 403 });
  }

  const supabase = createAdminClient();

  const { data, error } = await supabase
    .from("device_configs")
    .select("*")
    .eq("device_id", device.id)
    .order("version", { ascending: false })
    .limit(1)
    .single();

  if (error || !data) {
    return Response.json({ config: null, version: 0 });
  }

  return Response.json({
    config: data.config_json,
    configYaml: data.config_yaml,
    version: data.version,
    source: data.source,
    updatedAt: data.created_at,
  });
}

// POST — push config from device
export async function POST(request: Request) {
  const device = await authenticateDevice(request);
  if (!device) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (!device.capabilities.config) {
    return Response.json({ error: "Device does not support config" }, { status: 403 });
  }

  const body = await request.json();
  const { configYaml, configJson, version } = body;

  if (!configJson) {
    return Response.json({ error: "Missing configJson" }, { status: 400 });
  }

  const supabase = createAdminClient();

  // Check if server has a newer version from web
  const { data: latest } = await supabase
    .from("device_configs")
    .select("version, source")
    .eq("device_id", device.id)
    .order("version", { ascending: false })
    .limit(1)
    .single();

  const serverVersion = latest?.version ?? 0;
  const newVersion = Math.max(serverVersion, version ?? 0) + 1;

  // If server has a newer web-sourced version, web wins
  if (latest && latest.version > (version ?? 0) && latest.source === "web") {
    return Response.json({
      conflict: true,
      serverVersion: latest.version,
      message: "Server has a newer web-edited config. Pull first.",
    }, { status: 409 });
  }

  const { data, error } = await supabase
    .from("device_configs")
    .insert({
      device_id: device.id,
      config_yaml: configYaml ?? null,
      config_json: configJson,
      version: newVersion,
      source: "device",
    })
    .select()
    .single();

  if (error) {
    return Response.json({ error: "Failed to save config" }, { status: 500 });
  }

  return Response.json({ version: data.version, saved: true });
}

// PATCH — web app pushes config changes to device via command queue
const patchSchema = z.object({
  deviceId: z.string().uuid(),
  changes: z.record(z.string(), z.unknown()).refine((v) => Object.keys(v).length > 0, {
    message: "changes must not be empty",
  }),
});

export async function PATCH(request: Request) {
  // Session auth — this is a web user action, not a device call
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return Response.json({ error: "Not authenticated" }, { status: 401 });

  const body = await request.json().catch(() => null);
  const parsed = patchSchema.safeParse(body);
  if (!parsed.success) {
    return Response.json({ error: "Invalid body", details: parsed.error.flatten() }, { status: 400 });
  }

  const { deviceId, changes } = parsed.data;

  // Verify the user owns this device
  const { data: device, error: deviceError } = await supabase
    .from("devices")
    .select("id, capabilities")
    .eq("id", deviceId)
    .eq("user_id", user.id)
    .single();

  if (deviceError || !device) {
    return Response.json({ error: "Device not found" }, { status: 404 });
  }

  const admin = createAdminClient();

  // Fetch current config to build the merged snapshot
  const { data: latest } = await admin
    .from("device_configs")
    .select("config_json, version")
    .eq("device_id", deviceId)
    .order("version", { ascending: false })
    .limit(1)
    .single();

  const currentConfig = (latest?.config_json as Record<string, unknown>) ?? {};
  const currentVersion = latest?.version ?? 0;
  const mergedConfig = { ...currentConfig, ...changes };

  // Save new config version (source: web)
  const { data: saved, error: saveError } = await admin
    .from("device_configs")
    .insert({
      device_id: deviceId,
      config_json: mergedConfig,
      config_yaml: null, // regenerated by Pi on next pull
      version: currentVersion + 1,
      source: "web",
    })
    .select("version")
    .single();

  if (saveError || !saved) {
    return Response.json({ error: "Failed to save config" }, { status: 500 });
  }

  // Queue one set_config_field command per changed key
  const commands = Object.entries(changes).map(([key, value]) => ({
    device_id: deviceId,
    command: "set_config_field",
    params: { key, value },
    status: "pending",
  }));

  const { error: cmdError } = await admin.from("device_commands").insert(commands);
  if (cmdError) {
    return Response.json({ error: "Failed to queue commands" }, { status: 500 });
  }

  return Response.json({ version: saved.version, queued: commands.length });
}
